# The list of links is based on the code from das_download.rb, see https://gist.github.com/maca/1798070
# Just paste this into a PowerShell window and go.

$a = "https://www.destroyallsoftware.com/screencasts/catalog/routing-simple-requests", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/variables-in-routes", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/three-router-tweaks", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/first-attempt-at-database-library", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/a-compiler-from-scratch", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/data-compressor-from-scratch", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/text-editor-from-scratch", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/shell-from-scratch", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/http-server-from-scratch", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/malloc-from-scratch", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/introduction-to-computation", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/computing-by-changing", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/power-of-turing-machines", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/computing-by-constructing", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/power-of-lambda-calculus", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/the-limits-of-computation", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/recognizing-simple-languages", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/recognizing-programming-languages", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/the-most-complex-languages", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/final-notes-on-computation", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/collapsing-services-into-values", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/splitting-active-record-models", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/removing-a-rubinius-feature", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/python-vs-ruby-objects", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/where-correctness-is-enforced", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/separating-arrangement-and-work", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/primitive-obsession", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/isolating-by-separating-value", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/imperative-to-oo-to-functional", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/debugging-with-tests", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/test-cases-vs-examples", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/a-bit-of-c", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/analyzing-context-switches", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/actor-syntax-from-scratch", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/running-tests-asynchronously", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/test-recommendations", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/when-rails-is-right", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/a-day-in-the-life", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/sucks-rocks-1-the-rails-app", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/sucks-rocks-2-computing-scores", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/sucks-rocks-3-the-search-engine", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/sucks-rocks-4-caching", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/sucks-rocks-5-a-bug-and-a-model", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/sucks-rocks-6-a-controller", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/sucks-rocks-7-more-cucumber", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/sucks-rocks-8-the-whole-design", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/pretty-git-logs", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/mutation-in-tell-dont-ask", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/a-magical-isolation-story", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/ugly-tests-trigger-refactoring", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/the-mock-obsession-problem", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/test-driving-shell-scripts", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/conditional-whac-a-mole", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/time-to-first-request", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/test-isolation-without-mocks", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/functional-core-imperative-shell", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/what-goes-in-active-records", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/what-goes-in-active-records-part-2", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/outside-in-tdd-stubs-vs-stash", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/web-apps-when-to-test-in-isolation", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/untested-code-part-1-introduction", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/untested-code-part-2-adding-tests", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/untested-code-part-3-refactoring-1", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/untested-code-part-4-refactoring-2", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/emacs-chainsaw-of-chainsaws", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/stubbing-unloaded-dependencies", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/brittle-and-fragile-tests", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/repository-statistics-in-raptor", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/generating-coupons-with-bash", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/shorter-class-syntax", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/when-to-generalize-in-tdd", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/the-vimrc", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/pushing-complexity-down", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/three-test-shapes", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/composing-a-unix-command-line", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/tar-fork-and-the-tar-pipe", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/coupling-and-abstraction", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/test-isolation-and-refactoring", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/spiking-and-continuous-spiking", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/notes-on-stubbing", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/controller-refactoring-demo-part-1", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/controller-refactoring-demo-part-2", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/extracting-from-controller-to-model", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/acceptance-tests", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/extracting-from-models", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/some-vim-tips", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/history-spelunking-with-unix", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/performance-of-different-test-sizes", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/simple-bash-script-testing", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/splitting-into-fine-grained-tests", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/which-tests-to-write", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/tdding-spikes-away-with-rebase", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/statistics-over-git-repositories", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/how-and-why-to-avoid-nil", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/building-rspec-from-scratch", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/source-code-history-integrity", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/extracting-domain-objects", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/conflicting-principles", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/growing-a-test-suite", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/processes-and-jobs", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/exceptions-and-control-flow", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/fast-tests-with-and-without-rails", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/git-workflow", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/packaging-in-ruby-and-python", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/file-navigation-in-vim", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/extracting-objects-in-django", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/quick-and-easy-perf-tests", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/a-refactoring-story", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/wrapping-third-party-apis", 
                     "https://www.destroyallsoftware.com/screencasts/catalog/clarity-via-isolated-tests" 

for ($i=0; $i -le $a.length; $i++) { $html = Invoke-WebRequest $a[$i]; $scripts = $html.ParsedHtml.getElementsByTagName("script"); $match = [regex]::Match($scripts[2].text, 'https://destroyallsoftware.s3.amazonaws.com/.*4k.mp4.*\"'); $finalUri = $match.Value.Trim('"'); $fileName = "file$i.mp4"; Invoke-WebRequest -uri $finalUri -OutFile $fileName -UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"  }






